name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    env:
      GOLANGCI_LINT_VERSION: v1.21.0
    strategy:
      matrix:
        os:
          - macos-10.14
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Go environment
        uses: actions/setup-go@v1
        with:
          version: 1.13

      - name: Restore cache if available
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v1-

      - name: download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Restore golangci-lint if available
        uses: actions/cache@v1
        id: golangci-cache
        with:
          path: ./bin/
          key: ${{ runner.os }}-golangci-${{ env.GOLANGCI_LINT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-go-v1-

      - name: Install golangci-lint
        if: steps.golangci-cache.outputs.cache-hit != 'true'
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s $GOLANGCI_LINT_VERSION

      - name: Lint
        run: ./bin/golangci-lint run ./... -v

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./sample.alfredworkflow
